services:
  - name: sportify-backend
    type: web
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://saiedupulapati4:jmzLsxDWeHqA6noc@cluster0.whqrr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  - name: sportify-frontend
    type: web
    env: docker
    plan: free
    dockerfilePath: client/Dockerfile
    buildCommand: "npm run build"
    envVars:
      - key: REACT_APP_GOOGLE_CLIENT_ID
        value: 561537019638-8r5obepso26lld6cn7dq51o4334qs1g5.apps.googleusercontent.com